### ISSUE TITLE
A parameter cannot be found that matches parameter name 'ignoreUnchangedFiles'

### ISSUE THREAD

**Issue by menacestudio** [januskh/VSTS-FTPUploader#3]
We're getting an error when publishing through FTP.

`2017-09-22T21:02:33.9495032Z Executing the powershell script: E:\VSOAGENT\agent_2.11.05\_work\_tasks\FTPUploader_9b5ef860-d1ea-4d6e-9446-32487c223e54\1.0.28\FTPUpload.ps1
2017-09-22T21:02:34.3401314Z ##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'ignoreUnchangedFiles'.
2017-09-22T21:02:34.3401314Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2017-09-22T21:02:34.3401314Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2017-09-22T21:02:34.3401314Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2017-09-22T21:02:34.3401314Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-09-22T21:02:34.3401314Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2017-09-22T21:02:34.3401314Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2017-09-22T21:02:34.3557571Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.`

Thanks for any help.

**Comment by IanYates** [comment]
Broken in the last pull request.  It's annoying that VSTS auto-updates because the builds can break simply because of a change in an extension.

Anyway, I've just gone in, edited my build and ticked the box to put "true" into that new setting.  I don't need the feature so I've left it as true.

So there are two possible fixes

1. As an end-user, go update your build/release definitions.  I've just done this and am running the build again.  Hopefully it'll work 🤞 

2. @januskh or @thiagolunardi : If a new property is added, it needs to be done in a backwards compatible way.   I can see here - https://github.com/thiagolunardi/VSTS-FTPUploader/blob/a76de069838ce3adb2ee5b224b22d09a70aa8c9a/FTPUpload.ps1#L9 - that there was some attempt to make it not required.  That wasn't enough unfortunately.  I don't know enough about VSTS extension authoring to chime in on why it didn't work, and it's 11:30pm here so it's too late to research 😴

**Comment by IanYates** [comment]
Option 1 didn't work 😢

**Comment by IanYates** [comment]
It could be because the parameter I referenced in my earlier link didn't make it into the merged PS1 file in the repository.

Compare      https://github.com/januskh/VSTS-FTPUploader/blob/bff1405da1dd98a73684be06ca15d2d96471be7e/FTPUpload.ps1#L8
with
https://github.com/thiagolunardi/VSTS-FTPUploader/blob/a76de069838ce3adb2ee5b224b22d09a70aa8c9a/FTPUpload.ps1#L9

**Comment by IanYates** [comment]
Actually none of the changes to the FtpUpload.ps1 file made it in.

I've just patched it on my build server.  Hoping that'll do the trick.

**Comment by IanYates** [comment]
Success.  I just added in the missing parameter line.  I didn't include the many other changes in the file.  I'll wait for the next release.  In the meantime, adding the extra parameter at the top of the PS1 solves the "binding" issue as per `System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'ignoreUnchangedFiles'`

For you @menacestudio - go edit the file `E:\VSOAGENT\agent_2.11.05\_work\_tasks\FTPUploader_9b5ef860-d1ea-4d6e-9446-32487c223e54\1.0.28\FTPUpload.ps1` on your build server

**Comment by brunobertechini** [comment]
Same issue here -- annoying. How can I fix ?

Do I need to download and upload a new PS1 file ?

**Comment by brunobertechini** [comment]
Moving back to Microsofts FTP upload task in the meantime. Waiting for the fix in new version

Bruno

**Comment by IanYates** [comment]
@brunobertechini - on my build server I still had the PS1 file from the old version.  You can also get it from this repo as it hasn't changed (that's the problem).

So, on your build server, go find the PS1 file.  See my reply to @menacestudio for the rough path - it'll be under your agent's work / tasks folder.  Then edit the PS1 and make the parameters list look like

```
param(
    [string][Parameter(Mandatory=$true)]$sourcePath,
    [string][Parameter(Mandatory=$true)]$serverName,
    [string][Parameter(Mandatory=$true)]$username,
    [string][Parameter(Mandatory=$true)]$password,
    [string][Parameter(Mandatory=$true)]$remotePath,
    [string][Parameter(Mandatory=$true)]$useBinary,
    [string]$excludeFilter,
    [string]$ignoreUnchangedFiles,
    [string][Parameter(Mandatory=$true)]$deleteOldFiles,
    [string][Parameter(Mandatory=$true)]$deploymentFilesOnly
)
```

The extra line there is the `$ignoreUnchangedFiles` line.

Then VSTS should be happy to run the task as it can map every defined input with a parameter to the script.

**Comment by IanYates** [comment]
@januskh - any thoughts on this?

**Comment by januskh** [comment]
Yes... something has gone wrong in the merge... I believe that the problem should be fixed now. Please test and report back. Thank you. Sorry for the inconvenience and trouble this may have cost you. Thank you for reporting... I will buy you all a beer at the airport ;)

**Comment by rtenhoor** [comment]
Works for us now. Many thanks! I still much prefer this FTP Upload to the standard Microsoft one! (However, the automatic upgrade, which broke our standard uploads, did raise some concern here....)

**Comment by januskh** [comment]
That is the case with all of the custom extensions on VSO. If it breaks, everyone will have issues. Would have been nice with some kind of staging/testing environment before it’s pushed live. But good to know that it works again. Sorry for the trouble.

**Comment by IanYates** [comment]
@januskh - no problem.  I got to dig in and understand more about how this stuff all fits together.  Looking under the covers is never a bad thing :)  Not always fun when you hit the problem late at night of course but it was satisfying to solve myself in the end.

@rtenhoor - the easiest way to "roll back" is to look at your build server's folders where it downloads the tasks.  From there you can see the old versions of your various tasks.  You can overwrite files in the newer versions of tasks with those of older versions.  The VSTS agent doesn't seem to bother checking too much about the integrity of the tasks so it happily accepts that the files on disk are correct.  Not perfect, but it's a nice escape hatch I'll keep in mind for the future.

**Comment by rtenhoor** [comment]
Hi Ian, I think I cannot do this in VS-online... (or can I?). So, I believe in VSO online, you are at mercy of the automatic updates...

**Comment by IanYates** [comment]
@rtenhoor - I use VS Online but with my own build server.  I guess if you're using the hosted build servers then you're right, you don't really have the ability to log in and muck with the task files.

**Comment by IanYates** [comment]
Sigh...

The new version is on my build server but it's now broken in a different way
```

******************************************************************************
Starting: Upload using FTP
******************************************************************************
==============================================================================
Task         : FTP Uploader
Description  : For uploading files using FTP protocol.
Version      : 1.0.29
Author       : januskamphansen
Help         : 
==============================================================================
Preparing task execution handler.
Executing the powershell script: D:\Agent2\Work\_tasks\FTPUploader_9b5ef860-d1ea-4d6e-9446-32487c223e54\1.0.29\FTPUpload.ps1
System.Net.FtpWebResponse
Creating directories...
Uploading files...
Ignoring unchanged files...
System.Management.Automation.CommandNotFoundException: The term 'Has-Changes' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.CommandNotFoundException: The term 'Upload-File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.CommandNotFoundException: The term 'Has-Changes' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.CommandNotFoundException: The term 'Upload-File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.CommandNotFoundException: The term 'Has-Changes' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
System.Management.Automation.CommandNotFoundException: The term 'Upload-File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
PowerShell script completed with 6 errors.

```

I'll overwrite the contents again to get it working.

**Comment by IanYates** [comment]
Overwriting with the old version (plus the extra parameter), as described above, has it working again.  I don't have time to sift through and debug at the moment sorry.

**Comment by januskh** [comment]
Yes, don't use the "Ignore changed files"-feature. It's buggy.

**Comment by IanYates** [comment]
Ahh - yes, I still had that feature enabled as a by-product of my original attempts to fix.  Happily ignoring the functionality.
I'll disable and let it try again :)

Thanks!
